### ISSUE TITLE
add documentation on how to build and load the .jar file

### ISSUE THREAD

**Issue by codeforkjeff** [upenn-libraries/solrplugins#12]
Namely, that a line like this needs to be added to the `server/contexts/solr-jetty-context.xml` file:

```xml
<Set name="extraClasspath">/home/jeffchiu/solrplugins/target/solrplugins-0.1-SNAPSHOT.jar</Set>
```
I think loading the jar for distributed Solr is different? So it would be good to document that too.

**Comment by magibney** [comment]
Addressed by [commit efe8fc6](https://github.com/upenn-libraries/solrplugins/commit/efe8fc6e2)
